<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace GPBMetadata;

class Message
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a290a0d6d6573736167652e70726f746f12095465737450726f746f2205" .
            "0a034d7367620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

